### ISSUE TITLE
[CI] Update docker login step to work across forks and non-nasa-users

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#6890]
#### Summary
Current if a user creates a PR, the couchdb docker login step will fail due to restricted access to username/password
```yaml
   - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```
