### ISSUE TITLE
[e2e] Update visual test for imagery to attempt to use a routed image instead of one provided by the example imagery plugin

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7495]
#### Summary

When attempting to stabilize the visual tests, I attempted to intercept the network _response_ from the example imagery plugin. I filed the issue here: https://github.com/percy/percy-playwright/issues/313

There are two things left to try:
1. try using the `captureMockedServiceWorker: true` configuration in our percy file:
```
version: 2
snapshot:
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
  captureMockedServiceWorker: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
```
2. attempt to intercept the _request_ instead of the response.
